//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDataGenerator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public Food()
        {
            this.tbl_food_log = new HashSet<FoodLog>();
        }
    
        public string FoodID { get; set; }
        public string ParentID { get; set; }
        public string Name { get; set; }
        public Nullable<double> Quantity { get; set; }
    
        public virtual ICollection<FoodLog> tbl_food_log { get; set; }
    }
}
