//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDataGenerator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_food_nutrient_log
    {
        public int NutrientLogID { get; set; }
        public int FoodID { get; set; }
        public int NutrientID { get; set; }
        public decimal Value { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual tbl_nutrient Nutrient { get; set; }
    }
}
