//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDataGenerator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.tbl_activity_log = new HashSet<ActivityLog>();
            this.tbl_food_log = new HashSet<FoodLog>();
            this.tbl_metric_log = new HashSet<MetricLog>();
            this.tbl_user_target = new HashSet<UserTarget>();
        }
    
        public int UserID { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public sbyte Gender { get; set; }
        public string PasswordHash { get; set; }
        public string PasswordSalt { get; set; }
        public sbyte AdminInt { get; set; }
        public System.DateTime CreationTimestamp { get; set; }
        public int ActivityLevel { get; set; }
    
        public virtual ICollection<ActivityLog> tbl_activity_log { get; set; }
        public virtual ICollection<FoodLog> tbl_food_log { get; set; }
        public virtual ICollection<MetricLog> tbl_metric_log { get; set; }
        public virtual ICollection<UserTarget> tbl_user_target { get; set; }
    }
}
